# Generated by Django 3.2.18 on 2023-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Phonenumber', models.IntegerField()),
                ('Mailid', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Department', models.CharField(max_length=150)),
                ('Courses', models.CharField(max_length=200)),
                ('Purpose', models.CharField(max_length=200)),
                ('Materialsprovide', models.CharField(max_length=200)),
            ],
        ),
    ]
