# Generated by Django 3.2.18 on 2023-04-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Name',
            new_name='NAME',
        ),
    ]
